# VARIABLES
@baseUrl = http://localhost:3333

# GET ROOMS
GET {{baseUrl}}/rooms
###

# CREATE ROOM
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Room name test",
  "description": "room description test"
}
###

# GET ROOM QUESTIONS
GET {{baseUrl}}/rooms/0dbc2f98-4968-44be-4fdb-f399737e5e21/questions
###
