# VARIABLES
@baseUrl = http://localhost:3333

# GET ROOMS
# @name getRooms
GET {{baseUrl}}/rooms
###

# CREATE ROOM
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room name test",
  "description": "room description test"
}
###
@roomId = {{getRooms.response.body.$[0].id}}
###

# GET ROOM QUESTIONS
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
###

# CREATE Question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "This is a question test"
}
